12-12 11:05
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 117, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 40, in __init__
    self.btn_generate.config(state='normal')
AttributeError: 'NoneType' object has no attribute 'config'
12-12 11:05
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 117, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 40, in __init__
    self.btn_generate.config(state='normal')
AttributeError: 'NoneType' object has no attribute 'config'
12-12 11:07
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 118, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 41, in __init__
    self.btn_generate.config(state='normal')
AttributeError: 'NoneType' object has no attribute 'config'
12-12 14:18
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 140, in main
    Gui(BlockGenerator(instance_name='Test'))
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 24, in __init__
    self.block_generator = args[0] if valid_type else BlockGenerator()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 91, in __init__
    self.instance_name = 'self_made' if kwargs else kwargs['instance_name']
KeyError: 'instance_name'
12-12 15:26
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 152, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 44, in __init__
    self.entry_new_path = Entry(fm1, validatecommand=os.path.isfile(self.entry_new_path.get()))
AttributeError: 'Gui' object has no attribute 'entry_new_path'
12-12 15:30
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 152, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 44, in __init__
    self.entry_new_path = Entry(fm1, validcommand=lambda: self.btn_generate.config(state='normal'), validatecommand=lambda: os.path.isfile(self.entry_new_path.get()))
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2673, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-validcommand"
12-12 15:36
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 155, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 44, in __init__
    self.entry_new_path = Entry(fm1, validate=True, validatecommand=self.eval_gui_config)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2673, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: bad validate "1": must be all, key, focus, focusin, focusout, or none
12-12 15:37
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 156, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 44, in __init__
    self.entry_new_path = Entry(fm1, validate=True, validatecommand=self.eval_gui_config)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2673, in __init__
    Widget.__init__(self, master, 'entry', cnf, kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: bad validate "1": must be all, key, focus, focusin, focusout, or none
12-13 10:00
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 159, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 71, in __init__
    txt_log = Text(fm4, text="Test")
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3098, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-text"
12-13 10:51
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 167, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 71, in __init__
    txt_log = Text(fm4, wrap="None")
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3098, in __init__
    Widget.__init__(self, master, 'text', cnf, kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: bad wrap "None": must be char, none, or word
12-13 11:05
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 167, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 74, in __init__
    scrollbar_vert = Scrollbar(fm4, txt_log.yview)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3040, in __init__
    Widget.__init__(self, master, 'scrollbar', cnf, kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2289, in __init__
    BaseWidget._setup(self, master, cnf)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2261, in _setup
    if 'name' in cnf:
TypeError: argument of type 'method' is not iterable
12-13 15:14
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 184, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 90, in __init__
    lbl_search.pack(side=RIGHT, text='Search')
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2140, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: bad option "-text": must be -after, -anchor, -before, -expand, -fill, -in, -ipadx, -ipady, -padx, -pady, or -side
12-13 15:16
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 184, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 65, in __init__
    progressbar = Progressbar(fm3, style='black.Horizontal.TProgressbar', text='Idle')
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\ttk.py", line 1014, in __init__
    Widget.__init__(self, master, "ttk::progressbar", kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\ttk.py", line 559, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-text"
12-13 16:23
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 191, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 105, in __init__
    fm4.pack(side=TOP, fill=BOTH, expand=YES)
UnboundLocalError: local variable 'fm4' referenced before assignment
12-14 09:41
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 196, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 82, in __init__
    self.txt_log.bind('<Ctrl-f>', self.tab_hotkeys)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1248, in bind
    return self._bind(('bind', self._w), sequence, func, add)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1203, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: bad event type or keysym "Ctrl"
12-14 10:34
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 209, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 103, in __init__
    menubar.pack(side=TOP, fill=X)
  File "C:\Users\z003d8sd\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2140, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: can't pack ".!menu": it's a top-level window
12-14 10:34
Traceback (most recent call last):
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 210, in main
    Gui()
  File "C:/Users/z003d8sd/PycharmProjects/S5ToTmBlockGenerator/main.py", line 46, in __init__
    menubar.add_command(label="Hello!", command=hello)
NameError: name 'hello' is not defined
12-14 16:39
Traceback (most recent call last):
  File "G:/S5ToTmBlockGenerator/main.py", line 263, in main
    Gui()
  File "G:/S5ToTmBlockGenerator/main.py", line 114, in __init__
    self.repack_all()
  File "G:/S5ToTmBlockGenerator/main.py", line 144, in repack_all
    for w in self.pack_list:
AttributeError: 'Gui' object has no attribute 'pack_list'
12-14 16:40
Traceback (most recent call last):
  File "G:/S5ToTmBlockGenerator/main.py", line 262, in main
    Gui()
  File "G:/S5ToTmBlockGenerator/main.py", line 121, in __init__
    self.repack_all()
  File "G:/S5ToTmBlockGenerator/main.py", line 150, in repack_all
    expand=w['expand'] if w['expand'] else _,
KeyError: 'expand'
12-14 16:42
Traceback (most recent call last):
  File "G:/S5ToTmBlockGenerator/main.py", line 262, in main
    Gui()
  File "G:/S5ToTmBlockGenerator/main.py", line 121, in __init__
    self.repack_all()
  File "G:/S5ToTmBlockGenerator/main.py", line 150, in repack_all
    expand=w['expand'] if 'expand' in w.keys() else _,
NameError: name '_' is not defined
12-14 20:09
Traceback (most recent call last):
  File "H:/S5ToTmBlockGenerator/main.py", line 275, in main
    Gui()
  File "H:/S5ToTmBlockGenerator/main.py", line 56, in __init__
    separator = Frame(height=2, bd=1, relief=SUNKEN)
  File "C:\Users\EivindBrate\AppData\Local\Programs\Python\Python37\lib\tkinter\ttk.py", line 742, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "C:\Users\EivindBrate\AppData\Local\Programs\Python\Python37\lib\tkinter\ttk.py", line 559, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Users\EivindBrate\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-bd"
12-14 20:13
Traceback (most recent call last):
  File "H:/S5ToTmBlockGenerator/main.py", line 275, in main
    Gui()
  File "H:/S5ToTmBlockGenerator/main.py", line 56, in __init__
    separator = Frame(height=2, borderwidth=1, relief=GROOVE, pady=(2, 0))
  File "C:\Users\EivindBrate\AppData\Local\Programs\Python\Python37\lib\tkinter\ttk.py", line 742, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "C:\Users\EivindBrate\AppData\Local\Programs\Python\Python37\lib\tkinter\ttk.py", line 559, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Users\EivindBrate\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2296, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown option "-pady"
12-14 21:23
Traceback (most recent call last):
  File "H:/S5ToTmBlockGenerator/main.py", line 268, in main
    Gui()
  File "H:/S5ToTmBlockGenerator/main.py", line 121, in __init__
    self.connect_to_users()
  File "H:/S5ToTmBlockGenerator/main.py", line 125, in connect_to_users
    self.children[0] = BlockGenerator()
IndexError: list assignment index out of range
